wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: Flow Matching, UNet+Skips
dataset:
  desc: null
  value: Circles
epochs:
  desc: null
  value: 1000.0
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746103636.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.16.6
      8:
      - 5
      13: darwin-x86_64
